{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.1",
    "version": "0.0.7-fix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "size": 706936,
          "sha512": "a9dee4391cb911d316cf6aac8c18a9c1b5071cca82c71d6c3f871dfbdc40b1357ca0046b2dccf9f0cea91e3bc63e452d2cba4aafc7e4586d2ae587d5d99f1b0a",
          "sha256": "3ecaa9bd6c794b5439b746130449109516260370bcb94a57bede489135a75d2f",
          "sha1": "0871c6a5438e9c551c752f401ea9b6c4bebd6f1b",
          "md5": "9ab3a510865daacbca51beae82333b5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "size": 706936,
          "sha512": "a9dee4391cb911d316cf6aac8c18a9c1b5071cca82c71d6c3f871dfbdc40b1357ca0046b2dccf9f0cea91e3bc63e452d2cba4aafc7e4586d2ae587d5d99f1b0a",
          "sha256": "3ecaa9bd6c794b5439b746130449109516260370bcb94a57bede489135a75d2f",
          "sha1": "0871c6a5438e9c551c752f401ea9b6c4bebd6f1b",
          "md5": "9ab3a510865daacbca51beae82333b5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3-sources.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3-sources.jar",
          "size": 492670,
          "sha512": "11b1c4c4335a3024fdbb96e8559a3194315a5bb8fa83ba7ea508889f6ae4360b56d601d978311ecb5ce0deb9e10798a7ed5f3d38917232e7cbcda3595bb52abb",
          "sha256": "8d3dce87fe204ddfd1c6b1e1d8769b036b6e77d9ab965b2240eb3b31e4e24c25",
          "sha1": "d17d4ea675c3eb1756cb21498ab8f21d4cdd9ca8",
          "md5": "77b14a692d9b820f8cf897e34a291207"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3-javadoc.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3-javadoc.jar",
          "size": 1316635,
          "sha512": "a9319fcfc08fdfb1789569c3f31013f631a34b06ab6475b24f3c998ad475f9c227edd598226e7e17e022ceed372fe21df411800ca96c0e7b4443548ca2896b19",
          "sha256": "5070b9e80c2ac616ae545bb78130cd70bcdfbf4b2758c740971a1a167b90ddd8",
          "sha1": "9382415d4553caba0a9b8bef68a99b067ab9fe38",
          "md5": "a6e5a69c030b2043c24c743fd47a8e23"
        }
      ]
    }
  ]
}
