{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.1",
    "version": "0.0.7-fix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "size": 707044,
          "sha512": "2d158a41ff1e7797f6dd455af2f9e63d4e58ad87bc304c0b4fc887ac9ab817fdf8ba40483c0f0f18ff7fc85b9feeed41b305d5f32a8f91120bcafce76174999b",
          "sha256": "cadb98389e9f6715be9d52d7baa58b17f57e14b6ebbb1ebc690e587bebb6fff1",
          "sha1": "6e7206cdc0487fde494ea9ca207d33f94333fc87",
          "md5": "d97cc17616c729b93fa7e43af21aedf1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3.jar",
          "size": 707044,
          "sha512": "2d158a41ff1e7797f6dd455af2f9e63d4e58ad87bc304c0b4fc887ac9ab817fdf8ba40483c0f0f18ff7fc85b9feeed41b305d5f32a8f91120bcafce76174999b",
          "sha256": "cadb98389e9f6715be9d52d7baa58b17f57e14b6ebbb1ebc690e587bebb6fff1",
          "sha1": "6e7206cdc0487fde494ea9ca207d33f94333fc87",
          "md5": "d97cc17616c729b93fa7e43af21aedf1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3-sources.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3-sources.jar",
          "size": 493029,
          "sha512": "5cb0fa31962a5ceca076b49e1317e9a55c36fe26dc1c1872be6f7ec4efd3726cecc4f4d2d1ee17dc65bcd8d48d36025f51a7f445e8129b45fcd7a8342f70973c",
          "sha256": "d8d792a7c839ff7228ed4e5258c70c342ee8b94bd6130a08ae95b5f608ab31bb",
          "sha1": "2fc1b339249a34bdf3f09940c79ff98ba35086ae",
          "md5": "a44d56df3a063991ce64aab6601c185e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-fix3-javadoc.jar",
          "url": "numen-api-common-1.20.1-0.0.7-fix3-javadoc.jar",
          "size": 1317063,
          "sha512": "774d3c78063a4f1803f9b630f8e8993cfb4739e3dc4dc4233ea08f71d96e0b26eb31128dfbb5837d32143b0b47a70ab90245acdf8e39cef1e0113168f9c592ee",
          "sha256": "d15d0a720b797eddd74c087f2c8f0a93e3447ec4f34e85396ad9628cb23cc2a3",
          "sha1": "7fb4e86d3708c24be5db14c6bec265c2701093ee",
          "md5": "28f58410c2d1fba8ac90318de1c12745"
        }
      ]
    }
  ]
}
