{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.1",
    "version": "0.0.7-fix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "size": 738053,
          "sha512": "64604777a911938aa6531f89b56bf09473ea4ef85942af0311fedd4185aa7269b074d49e7b80b4200c8935ba14485b1f8dcbf54424280afff2c74810bf0e5241",
          "sha256": "26db342ef6cc59dda3481fb09a191d2626f25f440ebe510039ae6c937c6d0147",
          "sha1": "7d94fa3347ecff053443e0d88d596f613b1b5860",
          "md5": "a586617b84c376e39742d343a897a676"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "size": 738053,
          "sha512": "64604777a911938aa6531f89b56bf09473ea4ef85942af0311fedd4185aa7269b074d49e7b80b4200c8935ba14485b1f8dcbf54424280afff2c74810bf0e5241",
          "sha256": "26db342ef6cc59dda3481fb09a191d2626f25f440ebe510039ae6c937c6d0147",
          "sha1": "7d94fa3347ecff053443e0d88d596f613b1b5860",
          "md5": "a586617b84c376e39742d343a897a676"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3-sources.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3-sources.jar",
          "size": 512725,
          "sha512": "9efbce7f216b8a49beeff31732fb7ae391993206c5c4d3ccec458ec6cc3344325a852a5f12fc2bca2fd0f88222ec39a5250766ea0a60ce2cdeef73b56c08ba8c",
          "sha256": "7f8570ccd9efdca64f6eb92fb28449029c64183087a003473e734411200599b0",
          "sha1": "d2b8f74c97f4208c813dbb21a282177a3f431bf2",
          "md5": "d905fb55f34c13eca154d7d61ff5fa8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3-javadoc.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3-javadoc.jar",
          "size": 1363280,
          "sha512": "6da118546d72929b921766b30614467892c0eb1234cc3f40b216f956acc3e0534d518f16cc5b54edb8895cc4436e1f172666f612ca434bffca0b9fa4f256e498",
          "sha256": "6b8248f49e1e7009e3caab237a4fd0891416f07e8e5174e807552dd5685e0eda",
          "sha1": "18760e0c9fcbea098f8ba5c80c6a766ce9bcffe6",
          "md5": "bf62d081bb2b06a9104f78cad6084612"
        }
      ]
    }
  ]
}
