{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.1",
    "version": "0.0.7-fix3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "size": 738161,
          "sha512": "f4b8f15972431fa1504687e04a9f20018910fd7b8770112fd446724be45f0e0a7d42608b8fc5e5080f2c220466fcb3988aa71ae5f0481e6150fc8b8f28b9725b",
          "sha256": "7d3e1344fe038707af923d5d1a34b5865e90aa504dca02ed9120ed2055e857b0",
          "sha1": "6781fed398668a6e90fdbd21c5eba167b025a71d",
          "md5": "af4ade89a2a324e5ff6faa4cc6bab451"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3.jar",
          "size": 738161,
          "sha512": "f4b8f15972431fa1504687e04a9f20018910fd7b8770112fd446724be45f0e0a7d42608b8fc5e5080f2c220466fcb3988aa71ae5f0481e6150fc8b8f28b9725b",
          "sha256": "7d3e1344fe038707af923d5d1a34b5865e90aa504dca02ed9120ed2055e857b0",
          "sha1": "6781fed398668a6e90fdbd21c5eba167b025a71d",
          "md5": "af4ade89a2a324e5ff6faa4cc6bab451"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3-sources.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3-sources.jar",
          "size": 513084,
          "sha512": "14d00f62a174112de735d4383d6140b882199e96fd441e84a5160129a73ec8ed0b33057281d8892237af9a141a29222f01003977ffd14ba6897c3e57d85c28fe",
          "sha256": "5d5ca492d0a7cdc6a86dd2f984871e0baab00c696d03303b286d1b37adc8225a",
          "sha1": "c2670d795004b0ee34a4f385e1d278c27c979fb4",
          "md5": "494c13e9a42a85ab0ae0d9cf30c135b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-fix3-javadoc.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-fix3-javadoc.jar",
          "size": 1363682,
          "sha512": "827d9df015952b107a140e06b7f457104e0e4d8585f581e028de4fd9f1617f269e8227f9815ef7e070a3131380f95ab18f3ea979b4697237f3473bf8745e6528",
          "sha256": "036c685328758ea3ede0643f3323e8097c1163e2f305d2c949a8d1a2cd69bbb6",
          "sha1": "7f356e7562b951707b39046a1fffd8fd8447463c",
          "md5": "a89ea8c1320c4b7b066cebcfadb07f64"
        }
      ]
    }
  ]
}
